using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SpendSmart.Expense.API.Data;
using SpendSmart.Expense.API.Repositories;
using SpendSmart.Expense.API.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using System.Text;
using MassTransit;


var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();





builder.Services.AddDbContext<ExpenseDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.AddScoped<IExpenseRepository, ExpenseRepository>();
builder.Services.AddScoped<IExpenseService, ExpenseService>();
builder.Services.AddHttpClient();

// Enable validation of JWT Tokens
var key = Encoding.ASCII.GetBytes(builder.Configuration["Jwt:Secret"] ?? "SuperSecretKeyForSpendSmart123456789!");
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.RequireHttpsMetadata = false;
        options.SaveToken = true;
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = new SymmetricSecurityKey(key),
            ValidateIssuer = false,
            ValidateAudience = false
        };
    });

// MassTransit In-Memory Configuration
builder.Services.AddMassTransit(x =>
{
    x.UsingInMemory((context, cfg) =>
    {
        cfg.ConfigureEndpoints(context);
    });
});

var app = builder.Build();

// Auto-provision database at runtime (Bypasses EF Tooling issues)
try
{
    using (var scope = app.Services.CreateScope())
    {
        var context = scope.ServiceProvider.GetRequiredService<ExpenseDbContext>();
        try { context.Database.EnsureCreated(); } catch { }
        
        try
        {
            var sql = @"
            CREATE TABLE IF NOT EXISTS ""Expenses"" (
                ""ExpenseId"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""UserId"" integer NOT NULL,
                ""CategoryId"" integer NOT NULL,
                ""Amount"" numeric(18,2) NOT NULL,
                ""Currency"" text NOT NULL,
                ""Description"" text NOT NULL,
                ""Date"" timestamp with time zone NOT NULL,
                ""PaymentMode"" text NOT NULL,
                ""Tags"" text NOT NULL,
                ""ReceiptUrl"" text NULL,
                ""IsRecurring"" boolean NOT NULL,
                ""CreatedAt"" timestamp with time zone NOT NULL,
                ""UpdatedAt"" timestamp with time zone NULL,
                CONSTRAINT ""PK_Expenses"" PRIMARY KEY (""ExpenseId"")
            );
            CREATE INDEX IF NOT EXISTS ""IX_Expenses_UserId_Date"" ON ""Expenses"" (""UserId"", ""Date"");
            ";
            context.Database.ExecuteSqlRaw(sql);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[DB INIT] Raw SQL failed: {ex.Message}");
        }
    }
}
catch (Exception ex)
{
    Console.WriteLine($"[CRITICAL] Database initialization failed: {ex.Message}. Service will attempt to start regardless.");
}

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

app.Run();

